"""MIOSA Python SDK — desktop infrastructure for AI agents.

Usage::

    from miosa import Miosa

    client = Miosa(api_key="msk_u_...")
    computer = client.computers.create(name="my-agent")
    computer.start()
    screenshot = computer.screenshot()
"""

from .client import AsyncClient, AsyncMiosa, Client, Miosa
from .errors import (
    AuthenticationError,
    ConnectionError,
    InsufficientCreditsError,
    MiosaError,
    NotFoundError,
    PermissionError,
    RateLimitError,
    ServerError,
    TimeoutError,
    ValidationError,
)
from .types import (
    AgentEvent,
    AgentSession,
    AgentSessionStatus,
    Computer as ComputerModel,
    ComputerEvent,
    ComputerSize,
    ComputerStatus,
    ComputerVisibility,
    CreditBalance,
    CreditTransaction,
    CreditUsage,
    CursorPosition,
    CustomDomainData,
    CustomDomainStatus,
    Deployment,
    DeploymentBuild,
    DeploymentRelease,
    DeploymentService,
    DeploymentServiceType,
    DeploymentSourceType,
    DeploymentState,
    DeploymentVersion,
    DeploymentVersionKind,
    DeploymentVersionState,
    DirEntry,
    ExecResult,
    ExternalAttribution,
    FileInfo,
    FileStat,
    NetworkPolicyData,
    NetworkPolicyEffect,
    NetworkPolicyProtocol,
    NetworkPolicyRule,
    PreviewShareResult,
    PreviewState,
    PreviewVisibility,
    PublishResult,
    RuntimeInstance,
    RuntimeInstanceState,
    SandboxPreviewData,
    ServiceData,
    ServiceLogEvent,
    ServiceStatus,
    ScreenSize,
    SnapshotData,
    SnapshotProgressEvent,
    SnapshotStatus,
    WindowInfo,
    WorkspaceData,
)

__all__ = [
    # Clients
    "Miosa",
    "AsyncMiosa",
    "Client",
    "AsyncClient",
    # Errors
    "MiosaError",
    "AuthenticationError",
    "ConnectionError",
    "InsufficientCreditsError",
    "NotFoundError",
    "PermissionError",
    "RateLimitError",
    "ServerError",
    "TimeoutError",
    "ValidationError",
    # Types
    "AgentEvent",
    "AgentSession",
    "AgentSessionStatus",
    "ComputerEvent",
    "ComputerModel",
    "ComputerSize",
    "ComputerStatus",
    "ComputerVisibility",
    "CreditBalance",
    "CreditTransaction",
    "CreditUsage",
    "CursorPosition",
    "CustomDomainData",
    "CustomDomainStatus",
    "Deployment",
    "DeploymentBuild",
    "DeploymentRelease",
    "DeploymentService",
    "DeploymentServiceType",
    "DeploymentSourceType",
    "DeploymentState",
    "DeploymentVersion",
    "DeploymentVersionKind",
    "DeploymentVersionState",
    "DirEntry",
    "ExecResult",
    "ExternalAttribution",
    "FileInfo",
    "FileStat",
    "NetworkPolicyData",
    "NetworkPolicyEffect",
    "NetworkPolicyProtocol",
    "NetworkPolicyRule",
    "PreviewShareResult",
    "PreviewState",
    "PreviewVisibility",
    "PublishResult",
    "RuntimeInstance",
    "RuntimeInstanceState",
    "SandboxPreviewData",
    "ServiceData",
    "ServiceLogEvent",
    "ServiceStatus",
    "ScreenSize",
    "SnapshotData",
    "SnapshotProgressEvent",
    "SnapshotStatus",
    "WindowInfo",
    "WorkspaceData",
]

__version__ = "1.1.0"
