"""MIOSA Python SDK — desktop infrastructure for AI agents.

Usage::

    from miosa import Miosa

    client = Miosa(api_key="msk_u_...")
    computer = client.computers.create(name="my-agent")
    computer.start()
    screenshot = computer.screenshot()
"""

from ._version import __version__
from .agent_builds import (
    AGENT_BUILD_KIND_SPECS,
    DEFAULT_AGENT_BUILD_OUTPUT_ROOT,
    DEFAULT_AGENT_BUILD_PACKET_VERSION,
    create_agent_build_execution_packet,
    create_agent_build_expected_outputs,
    create_agent_build_instruction,
    create_build_run_params,
    get_agent_build_kind_spec,
    resolve_agent_build_kind,
)
from .client import AsyncClient, AsyncMiosa, Client, Miosa
from .errors import (
    AuthenticationError,
    ConnectionError,
    EgressHostNotAllowedError,
    InstallationRequiredError,
    InsufficientCreditsError,
    ManagedProviderBindingOnlyError,
    MiosaError,
    NotFoundError,
    PermissionError,
    ProjectNotLinkedError,
    RateLimitError,
    ScopeNotAllowedError,
    ServerError,
    SubjectNotAllowedError,
    TimeoutError,
    TokenRefreshFailedError,
    UserAuthorizationRequiredError,
    ValidationError,
)
from .resources.computer import AsyncComputer, Computer
from .resources.forge import (
    AsyncForge,
    AsyncForgeRepositories,
    Forge,
    ForgeContractError,
    ForgePolicyViolationError,
    ForgeRepositories,
    ForgeRepository,
    ForgeRepositoryState,
    ForgeRepositoryVisibility,
    ForgeStorageError,
    ForgeUnavailableError,
)
from .resources.sandboxes import AsyncSandbox, Sandbox
from .types import (
    AgentEvent,
    AgentSession,
    AgentSessionStatus,
    ComputerEvent,
    ComputerSize,
    ComputerStatus,
    ComputerVisibility,
    CreditBalance,
    CreditTransaction,
    CreditUsage,
    CursorPosition,
    CustomDomainData,
    CustomDomainStatus,
    Deployment,
    DeploymentBuild,
    DeploymentRelease,
    DeploymentService,
    DeploymentServiceType,
    DeploymentSourceType,
    DeploymentState,
    DeploymentVersion,
    DeploymentVersionKind,
    DeploymentVersionState,
    DirEntry,
    DockerDeployApplianceStatus,
    DockerDeployHost,
    DockerDeployHostStatus,
    ExecResult,
    ExternalAttribution,
    FileInfo,
    FileStat,
    NetworkPolicyData,
    NetworkPolicyEffect,
    NetworkPolicyProtocol,
    NetworkPolicyRule,
    PreviewShareResult,
    PreviewState,
    PreviewVisibility,
    PublishResult,
    RuntimeInstance,
    RuntimeInstanceState,
    SandboxPreviewData,
    ScreenSize,
    ServiceData,
    ServiceLogEvent,
    ServiceStatus,
    SnapshotData,
    SnapshotProgressEvent,
    SnapshotStatus,
    WindowInfo,
    WorkspaceData,
)
from .types import (
    Computer as ComputerModel,
)

__all__ = [
    "__version__",
    # Clients
    "Miosa",
    "AsyncMiosa",
    "Client",
    "AsyncClient",
    "Computer",
    "AsyncComputer",
    "Forge",
    "AsyncForge",
    "ForgeRepositories",
    "AsyncForgeRepositories",
    "ForgeContractError",
    "ForgePolicyViolationError",
    "ForgeRepository",
    "ForgeRepositoryState",
    "ForgeRepositoryVisibility",
    "ForgeStorageError",
    "ForgeUnavailableError",
    "Sandbox",
    "AsyncSandbox",
    # Agent build helpers
    "AGENT_BUILD_KIND_SPECS",
    "DEFAULT_AGENT_BUILD_OUTPUT_ROOT",
    "DEFAULT_AGENT_BUILD_PACKET_VERSION",
    "create_agent_build_execution_packet",
    "create_agent_build_expected_outputs",
    "create_agent_build_instruction",
    "create_build_run_params",
    "get_agent_build_kind_spec",
    "resolve_agent_build_kind",
    # Errors
    "MiosaError",
    "AuthenticationError",
    "ConnectionError",
    "EgressHostNotAllowedError",
    "InstallationRequiredError",
    "InsufficientCreditsError",
    "ManagedProviderBindingOnlyError",
    "NotFoundError",
    "PermissionError",
    "ProjectNotLinkedError",
    "RateLimitError",
    "ScopeNotAllowedError",
    "ServerError",
    "SubjectNotAllowedError",
    "TimeoutError",
    "TokenRefreshFailedError",
    "UserAuthorizationRequiredError",
    "ValidationError",
    # Types
    "AgentEvent",
    "AgentSession",
    "AgentSessionStatus",
    "ComputerEvent",
    "ComputerModel",
    "ComputerSize",
    "ComputerStatus",
    "ComputerVisibility",
    "CreditBalance",
    "CreditTransaction",
    "CreditUsage",
    "CursorPosition",
    "CustomDomainData",
    "CustomDomainStatus",
    "Deployment",
    "DeploymentBuild",
    "DeploymentRelease",
    "DeploymentService",
    "DeploymentServiceType",
    "DeploymentSourceType",
    "DeploymentState",
    "DeploymentVersion",
    "DeploymentVersionKind",
    "DeploymentVersionState",
    "DirEntry",
    "DockerDeployApplianceStatus",
    "DockerDeployHost",
    "DockerDeployHostStatus",
    "ExecResult",
    "ExternalAttribution",
    "FileInfo",
    "FileStat",
    "NetworkPolicyData",
    "NetworkPolicyEffect",
    "NetworkPolicyProtocol",
    "NetworkPolicyRule",
    "PreviewShareResult",
    "PreviewState",
    "PreviewVisibility",
    "PublishResult",
    "RuntimeInstance",
    "RuntimeInstanceState",
    "SandboxPreviewData",
    "ServiceData",
    "ServiceLogEvent",
    "ServiceStatus",
    "ScreenSize",
    "SnapshotData",
    "SnapshotProgressEvent",
    "SnapshotStatus",
    "WindowInfo",
    "WorkspaceData",
]
